#!/usr/bin/env bash
#This is a script that prints Best School using while loop but prints bad luck on the 4th iteration and good luck on the 8th
counter=1
while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
