#!/usr/bin/env bash
#This script displays numbers from 1 -20 with very specific requirements
counter=1
while [ $counter -le 20 ]; do
	case $counter in
		4) 
			echo "4"
			echo "bad luck from china"
			;;
		9)
			echo "9"
			echo "bad luck from japan"
			;;
		17)
			echo "17"
			echo "bad luck from italy"
			;;
		*)
			echo "$counter"
	esac
	((counter++))
done
